AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 160

Naming/ConstantName:
  Enabled: False

Style/AsciiComments:
  AllowedChars: [ä]

Style/MutableConstant:
  Enabled: False

Style/SymbolArray:
  EnforcedStyle: brackets
